"""Add bookmarks table2

Revision ID: 667756347ffb
Revises: 8575243375ae
Create Date: 2023-09-25 09:25:07.653223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '667756347ffb'
down_revision: Union[str, None] = '8575243375ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('book_mark_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('literature_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bookmark_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('place', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.literature_id'], name='bookmark_literature_id_fkey'),
    sa.PrimaryKeyConstraint('book_mark_id', name='bookmark_pkey')
    )
    # ### end Alembic commands ###
