"""Add bookmarks table4

Revision ID: 837326013e81
Revises: d399184a6bf4
Create Date: 2023-09-25 10:36:49.105799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '837326013e81'
down_revision: Union[str, None] = 'd399184a6bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('book_mark_id', sa.Integer(), nullable=False),
    sa.Column('literature_id', sa.Integer(), nullable=False),
    sa.Column('bookmark_title', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('place', sa.JSON(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.literature_id'], ),
    sa.PrimaryKeyConstraint('book_mark_id')
    )
    op.alter_column('literature', 'add_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('literature', 'add_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('bookmark')
    # ### end Alembic commands ###
