"""Add bookmarks table

Revision ID: 8575243375ae
Revises: 99baf6c693c4
Create Date: 2023-09-25 09:00:32.621366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8575243375ae'
down_revision: Union[str, None] = '99baf6c693c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('book_mark_id', sa.Integer(), nullable=False),
    sa.Column('literature_id', sa.Integer(), nullable=False),
    sa.Column('bookmark_title', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('place', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.literature_id'], ),
    sa.PrimaryKeyConstraint('book_mark_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark')
    # ### end Alembic commands ###
