"""Add bookmarks table

Revision ID: 99baf6c693c4
Revises: 
Create Date: 2023-09-25 08:58:50.642630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '99baf6c693c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('literature',
                    sa.Column('literature_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('add_date', sa.TIMESTAMP(), nullable=False),
                    sa.Column('last_use_date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('original_literature_path', sa.String(), nullable=False),
                    sa.Column('parsed_literature_object', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('literature_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('literature')
    # ### end Alembic commands ###
