"""empty message

Revision ID: 1951d1969f75
Revises: 
Create Date: 2024-02-12 22:40:44.122562

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1951d1969f75"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "literature_epub",
        sa.Column("cover", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("original_file", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_opened_at", sa.DateTime(), nullable=True),
        sa.Column("last_read_position", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "literature_pdf",
        sa.Column("cover", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("original_file", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_opened_at", sa.DateTime(), nullable=True),
        sa.Column("last_read_position", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pdf_page_img",
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("literature_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["literature_id"],
            ["literature_pdf.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pdf_page_img")
    op.drop_table("literature_pdf")
    op.drop_table("literature_epub")
    # ### end Alembic commands ###
