"""empty message

Revision ID: 025280ebb29b
Revises: c86422fc54b8
Create Date: 2024-01-31 17:41:48.951705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "025280ebb29b"
down_revision: Union[str, None] = "c86422fc54b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pdf_page_img")
    op.drop_table("literature_pdf")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "literature_pdf",
        sa.Column(
            "original_pdf", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_opened_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('literature_pdf_id_seq'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="literature_pdf_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "pdf_page_img",
        sa.Column(
            "page_number", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "literature_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["literature_id"],
            ["literature_pdf.id"],
            name="pdf_page_img_literature_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="pdf_page_img_pkey"),
    )
    # ### end Alembic commands ###
